### PR TITLE
Global machine and some improvements

### PR DESCRIPTION
**Pull request by jxskiss**
Hi, I used this awsome library in a django project few days ago, to small down the big memory footprint, I modified the Fysom to a global machine.

Now I have successfully merged the changes back and thought there may be other people interest with this.

Changes:
1. New FysomGlobal and FysomGlobalMixin classes.
2. Add support to the more pythonic snake_case naming conversion to existing Fysom class (and FysomGlobal too, of course).
3. Add optional event attribute to the FysomError class.

The FysomGlobal is slightly different with Fysom:
- The initial state will only be automatically triggered for class derived with FysomGlobalMixin, else should be triggered manually
- Conditions and conditional transitions are implemented. This can be implemented for Fysom too if needed.
- When an event/transition is canceled, the event object will be  attached to the raised fysom.Canceled exception. By doing this, additional information can be passed through the exception.

I have updated the readme file and the tests with 100% coverage.

Thanks you people's great work!

### CODE REVIEW

**Comment by jxskiss** [comment]
@mriehl Hi, is there any consideration to accept this PR? Or I'd better post the extended machine as a separate package?

**Comment by mriehl** [comment]
Hi, apologies for the delay, I’m swamped with github notifications. I’ll try to have a look first thing tomorrow morning.

As long as it doesn’t break backwards compatibility I’ll merge if it looks ok for sure.
Thanks for taking the time to babysit the pull request!

**Comment by mriehl** [comment]
Looks cool. I'm merging this and will squeeze in a release today. Thanks @jxskiss

**Comment by jxskiss** [comment]
Nice, thanks!

**Pull request merged**
