### PR TITLE
Import ABC from collections.abc instead of collections for Python 3 compatibility

### LINKED ISSUE #41: Importing ABC directly from collections was removed in Python 3.9
https://github.com/mriehl/fysom/blob/5b2a27f05ebca200b9002b3e4fc699b7aebe4f0f/src/main/python/fysom/__init__.py#L162

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #41

### CODE REVIEW

**Comment by nmichaels-cc** [comment]
This has been here for well over a year. Is this project in need of a new maintainer?

**Comment by mriehl** [comment]
> This has been here for well over a year. Is this project in need of a new maintainer?

Yeah sort of. Sorry for dropping the ball on this, I haven't been using python for anything serious in the last years so I'm a bit out of the loop.
I am merging this and I'll look into making a pypi release this week end.

**Comment by mriehl** [comment]
I release 2.1.6 to PyPI with this fix. Sorry for the >1year wait.

**Comment by tirkarthi** [comment]
Thanks @mriehl

**Pull request merged**
